spring:
  redis:
    timeout: 6000
    cluster:
      max-redirects: 3 # 获取失败 最大重定向次数
      nodes:
        - redis7001:7001
    #        - 192.168.3.162:7001
    #        - 192.168.3.162:7002
    #        - 192.168.3.162:7003
    #        - 192.168.3.162:7004
    #        - 192.168.3.162:7005
    #        - 192.168.3.162:7006
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  cache:
    jcache:
      config: classpath:ehcache.xml
#  mvc:
#    view:
#      prefix: /pages/
#      suffix: .html
server:
  port: 80

express:
  isSwitchExceptionClass: true
  switchFlag: true
  goException: true

  goGoException: true
#  gogoException: true
#  go-go-exception: true
  goexceptions: true
#  ceShi: true
  ceshi: true
#  ce-shi: true